import { workspaceRootUri } from "../../utils/FileSystem";
import * as vscode from "vscode";
import path = require("path");

export const icons = new Map<string, string>([
    [
        "Crate",
        path.join(
            __filename,
            "..",
            "..",
            "..",
            "..",
            "resources",
            "icons",
            "vs",
            "Crate.svg"
        ),
    ],
    [
        "ModuleDirectory",
        path.join(
            __filename,
            "..",
            "..",
            "..",
            "..",
            "resources",
            "icons",
            "vs",
            "ModuleDirectory.svg"
        ),
    ],
    [
        "ModuleFile",
        path.join(
            __filename,
            "..",
            "..",
            "..",
            "..",
            "resources",
            "icons",
            "vs",
            "ModuleFile.svg"
        ),
    ],
    [
        "Reference",
        path.join(
            __filename,
            "..",
            "..",
            "..",
            "..",
            "resources",
            "icons",
            "vs",
            "reference.svg"
        ),
    ],
]);
